[package]
name = "kct"
description = "Kubernetes Configuration Tool"
keywords = ["kubernetes", "jsonnet"]
categories = ["command-line-utilities"]
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.1.7", features = ["derive"] }
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.16"

anyhow.workspace = true
kct_cli.workspace = true
kct_compiler.workspace = true
kct_helper.workspace = true
kct_kube.workspace = true
kct_package.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
