[package]
name = "kct"
version = "0.3.1"
edition = "2018"
authors = ["Bruno Felipe Leal Delfino <bruno.delfino1995@gmail.com>"]
description = "Kubernetes Configuration Tool"
repository = "https://github.com/bruno-delfino1995/kct"
license = "MIT"
keywords = ["kubernetes", "jsonnet"]
categories = ["command-line-utilities"]

[dependencies]
clap = "2.33.3"
flate2 = "1.0.17"
kct_helper = { path = "../crates/kct_helper", version = "^0.3.1"}
kct_kube = { path = "../crates/kct_kube", version = "^0.3.1"}
kct_package = { path = "../crates/kct_package", version = "^0.3.1"}
serde = "1.0.115"
serde_json = "1.0"
serde_yaml = "0.8"
tar = "0.4.30"
thiserror = "1.0"
